// Code generated by go generate; DO NOT EDIT.
package lpddr5

import (
	"waveconv/pkg/patconverter/timingcheck/ddr5checker/model/mrstatusreg"
)

const (
	
		Name_MR_0 = "MR0"
	
		Name_MR_1 = "MR1"
	
		Name_MR_2 = "MR2"
	
		Name_MR_3 = "MR3"
	
		Name_MR_4 = "MR4"
	
		Name_MR_5 = "MR5"
	
		Name_MR_6 = "MR6"
	
		Name_MR_7 = "MR7"
	
		Name_MR_8 = "MR8"
	
		Name_MR_9 = "MR9"
	
		Name_MR_10 = "MR10"
	
)

// DDR5MRS 實作
type LPDDR5MRS struct {
	mrstatusreg.BaseMRS
}

func NewLPDDR5MRS() *LPDDR5MRS {
	return &LPDDR5MRS{BaseMRS: mrstatusreg.BaseMRS{Mrs: make(map[string]mrstatusreg.MR)}}
}

func (m *LPDDR5MRS) Add(regname uint32, mrvalue uint8) bool {
	name := mrstatusreg.RegName(regname)
	switch name {
	case Name_MR_0:
		m.BaseMRS.Mrs[Name_MR_0] = &MR0{v: mrvalue}
	case Name_MR_1:
		m.BaseMRS.Mrs[Name_MR_1] = &MR1{v: mrvalue}
	case Name_MR_8:
		m.BaseMRS.Mrs[Name_MR_8] = &MR8{v: mrvalue}
	}
	return true
}

