// Code generated by go generate; DO NOT EDIT.
package ddr5

import (
	"waveconv/pkg/patconverter/timingcheck/ddr5checker/model/mrstatusreg"
)

var (
	
		Name_MR_0 = "MR0"
	
		Name_MR_1 = "MR1"
	
		Name_MR_2 = "MR2"
	
		Name_MR_3 = "MR3"
	
		Name_MR_4 = "MR4"
	
		Name_MR_5 = "MR5"
	
		Name_MR_6 = "MR6"
	
		Name_MR_7 = "MR7"
	
		Name_MR_8 = "MR8"
	
		Name_MR_9 = "MR9"
	
		Name_MR_10 = "MR10"
	
		Name_MR_11 = "MR11"
	
		Name_MR_12 = "MR12"
	
		Name_MR_13 = "MR13"
	
		Name_MR_14 = "MR14"
	
		Name_MR_15 = "MR15"
	
		Name_MR_16 = "MR16"
	
		Name_MR_17 = "MR17"
	
		Name_MR_18 = "MR18"
	
		Name_MR_19 = "MR19"
	
		Name_MR_20 = "MR20"
	
		Name_MR_21 = "MR21"
	
		Name_MR_22 = "MR22"
	
		Name_MR_23 = "MR23"
	
		Name_MR_24 = "MR24"
	
		Name_MR_25 = "MR25"
	
		Name_MR_26 = "MR26"
	
		Name_MR_27 = "MR27"
	
		Name_MR_28 = "MR28"
	
		Name_MR_29 = "MR29"
	
		Name_MR_30 = "MR30"
	
)


// DDR5MRS 實作
type DDR5MRS struct {
	mrstatusreg.BaseMRS
}

func NewDDR5MRS() *DDR5MRS {
	return &DDR5MRS{BaseMRS: mrstatusreg.BaseMRS{Mrs: make(map[string]mrstatusreg.MR)}}
}

func (m *DDR5MRS) Add(regname uint32, mrvalue uint8) bool {
	name := mrstatusreg.RegName(regname)
	switch name {
	case Name_MR_0:
		m.BaseMRS.Mrs[Name_MR_0] = &MR0{v: mrvalue}
	case Name_MR_1:
		m.BaseMRS.Mrs[Name_MR_1] = &MR1{v: mrvalue}
	case Name_MR_2:
		m.BaseMRS.Mrs[Name_MR_2] = &MR2{v: mrvalue}
	case Name_MR_8:
		m.BaseMRS.Mrs[Name_MR_8] = &MR8{v: mrvalue}
	case Name_MR_30:
		m.BaseMRS.Mrs[Name_MR_30] = &MR30{v: mrvalue}
	}
	
	return true
}

